server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 172.18.0.4
    port: 5672
    username: guest
    password: guest
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/Documents/SideProject/ProjectPractice/PracticeProject/native-file-repo
        git:
          uri: https://github.com/YEASEUL-JANG/spring-cloud-config
          default-label: master


management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh