server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      default-filters:
        - name: CorsFilter
      routes:
        ########## USER SERVICE
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/** # 액추에이터 정보
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        -  id: user-service
           uri: lb://USER-SERVICE
           predicates:
             - Path=/user-service/login #로그인 (실제 contoller에 없는 api, 스프링시큐리티에서 제공된 login api를 사용)
             - Method=POST
           filters:
             - RemoveRequestHeader=Cookie
             - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        -  id: user-service
           uri: lb://USER-SERVICE
           predicates:
             - Path=/user-service/users #회원가입
             - Method=POST
           filters:
             - RemoveRequestHeader=Cookie
        -  id: user-service
           uri: lb://USER-SERVICE
           predicates:
             - Path=/user-service/** #그 외 나머지 요청 (요청 헤더안에 인증토큰있는지 검증)
             - Method=GET
           filters:
             - name: LoggingFilter
               args:
                 msName: USER-SERVICE
                 requestLogger: true
                 responseLogger: true
             - RemoveRequestHeader=Cookie
             - AuthorizationHeaderfilter

        ########## POD SERVICE
        - id: pod-service
          uri: lb://POD-SERVICE
          predicates:
            - Path=/pod-service/actuator/** # 액추에이터 정보
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/pod-service/(?<segment>.*),/$\{segment}
        - id: pod-service
          uri: lb://POD-SERVICE
          predicates:
            - Path=/pod-service/**
          filters:
            - name: LoggingFilter
              args:
                msName: POD-SERVICE
                requestLogger: true
                responseLogger: true
            - RemoveRequestHeader=Cookie
            #- AuthorizationHeaderfilter

        ########## DEPLOYMENT SERVICE
        - id: deployment-service
          uri: lb://DEPLOYMENT-SERVICE
          predicates:
            - Path=/deployment-service/actuator/** # 액추에이터 정보
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: deployment-service
          uri: lb://DEPLOYMENT-SERVICE
          predicates:
            - Path=/deployment-service/**
          filters:
            - name: LoggingFilter
              args:
                msName: DEPLOYMENT-SERVICE
                requestLogger: true
                responseLogger: true
            - RemoveRequestHeader=Cookie
            #- AuthorizationHeaderfilter

        ########## SERVICE SERVICE
        - id: service-service
          uri: lb://SERVICE-SERVICE
          predicates:
            - Path=/service-service/actuator/** # 액추에이터 정보
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: service-service
          uri: lb://SERVICE-SERVICE
          predicates:
            - Path=/service-service/**
            - Method=GET,POST
          filters:
            - name: LoggingFilter
              args:
                msName: SERVICE-SERVICE
                requestLogger: true
                responseLogger: true
            - RemoveRequestHeader=Cookie
            #- AuthorizationHeaderfilter






management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh,info,metrics,prometheus
